# Generated by Django 2.2.5 on 2019-10-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.TextField(),
        ),
    ]
