# Generated by Django 2.2.5 on 2019-10-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191004_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='icon',
            new_name='logo_image',
        ),
    ]
