# Generated by Django 2.2.5 on 2019-10-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191006_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='logo_image',
            new_name='icon',
        ),
    ]
