# Generated by Django 2.2.5 on 2019-10-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191006_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='votes_total',
            field=models.IntegerField(),
        ),
    ]
