# Generated by Django 2.2.5 on 2019-10-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191007_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
    ]
